[package]
name = "extism-py"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
directories = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
rustpython-parser = "0.4.0"
structopt = "0.3.26"
tempfile = "3.12.0"
wagen = "0.2.0"
wizer = "7.0.0"
